[package]
name = "bullet"
version = "0.1.0"
authors = ["Darren Burns <darrenb900@gmail.com>"]

[dependencies]
rustbox = "*"
termbox-sys = "0.2.9"
quick-error = "1.2.0"

[dev-dependencies]
stainless = "*"